### ISSUE TITLE
Progress

### ISSUE THREAD

**Issue by tim-deighton** [jayprajapati857/ngx-uploader-directive#13]
Progress % for each individual file seems to be incorrect.
The value seems to to taken from overall progress

**Comment by jayprajapati857** [comment]
HI @tim-deighton I am looking at it and will back to you on this issue soon.

Thank you

**Comment by jayprajapati857** [comment]
Hi @tim-deighton in the uploader whenever you upload the files it gives the progress object with each file at the moment but that progress percentage is not for that file its for the whole request.

So whenever we upload the files to the server it gives the upload progress of whole request not for the individual file so that our uploader also provides the percentage of whole request and not for each individual file and if you want to get the upload percentage of each individual file then you must upload single file in a single request by setting options like this:

```ts
this.options = { requestConcurrency: 1, maxFilesToAddInSingleRequest: 1 };
```

The rest parameters if you want to set you can set to this options but to get the single files upload percentage you should set options like this and you should read the upload percentage from the output event and from IUploadOutput object, I mean from this function 

```ts
onUploadOutput(output: IUploadOutput): void {
    console.log(output);
    switch (output.type) {
      case 'init':
        this.files = new Array<ISelectedFile>();
        break;
      case 'allAddedToQueue':
        // uncomment this if you want to auto upload files when added
        // this.startUpload();
        break;
      case 'addedToQueue':
        this.files = this.files.concat(output.files);
        break;
      case 'start':
        // uploading start
        break;
      case 'uploading':
        this.files = this.updateFiles(this.files, output.files, output.progress, 'UPDATE');
        console.log(output.progress);
        break;
      case 'removed':
        this.files = this.updateFiles(this.files, output.files, output.progress, 'REMOVE');
        console.log(this.files);
        break;
      case 'removedAll':
        this.files = new Array<ISelectedFile>();
        // console.log(this.files);
        break;
      case 'dragOver':
        this.dragOver = true;
        break;
      case 'dragOut':
      case 'drop':
        this.dragOver = false;
        break;
      case 'done':
        // The files are uploaded
        this.files = this.updateFiles(this.files, output.files, output.progress, 'UPDATE');
        // console.log(this.files);
        break;
      case 'error':
        console.log(output);
        break;
    }
  }
```

You can read output progress from uploading type as I have put a console.log for output progress.

Thank you and I am closing this issue now if you still have doubt you can put the comments here or you can open issue again.
